package simulador;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ventanaVotoCompleto extends javax.swing.JFrame {

    private Fondo fondo = new Fondo();

    public ventanaVotoCompleto() {
        setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("ELECCIONES 2023");
        Image icono = new ImageIcon(getClass().getResource("/img/icono.png")).getImage();
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoletaIngresar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        botonListaSanMartin = new javax.swing.JButton();
        botonListaAvellaneda = new javax.swing.JButton();
        botonListaBelgrano = new javax.swing.JButton();
        botonListaGuemes = new javax.swing.JButton();
        botonListaMoreno = new javax.swing.JButton();
        botonListaRivadavia = new javax.swing.JButton();
        botonListaRoca = new javax.swing.JButton();
        botonListaPenia = new javax.swing.JButton();
        botonListaSaavedra = new javax.swing.JButton();
        botonListaSarmiento = new javax.swing.JButton();
        panelBarraOpciones = new javax.swing.JPanel();
        botonVolverAtras = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonVotoBlanco = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        logoProvincia11 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        panelBoletaIngresar.setBackground(new java.awt.Color(255, 255, 255));
        panelBoletaIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelBoletaIngresar.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("<html>Presidente: Moreno<br> Gobernador: Gauss<html>");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Moreno.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sarmiento.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Avellaneda.png"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Belgrano.png"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guemes.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SanMartin.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rivadavia.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Roca.png"))); // NOI18N
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RoqueSaenzPeña.png"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Saavedra.png"))); // NOI18N
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("<html>Presidente: Saavedra<br> Gobernador: Mitre<html>");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, -1, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("<html>Presidente: Avellaneda<br> Gobernador: B. Franklin<html>");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("<html>Presidente: Belgrano<br> Gobernador: Roosevelt<html>");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("<html>Presidente: Güemes<br> Gobernador: Tesla<html>");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("<html>Presidente: San Martín<br> Gobernador: Lavalle<html>");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("<html>Presidente: Rivadavia<br> Gobernador: Cortázar<html>");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("<html>Presidente: Roca<br> Gobernador: Newton<html>");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("<html>Presidente: Sarmiento<br> Gobernador: Rosas<html>");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, -1, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("<html>Presidente: Saenz Peña<br> Gobernador: Pellegrini<html>");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, 40));

        botonListaSanMartin.setBackground(new java.awt.Color(255, 255, 255));
        botonListaSanMartin.setForeground(new java.awt.Color(0, 0, 0));
        botonListaSanMartin.setBorderPainted(false);
        botonListaSanMartin.setFocusCycleRoot(true);
        botonListaSanMartin.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaSanMartin.setRequestFocusEnabled(false);
        botonListaSanMartin.setRolloverEnabled(false);
        botonListaSanMartin.setSelected(true);
        botonListaSanMartin.setVerifyInputWhenFocusTarget(false);
        botonListaSanMartin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaSanMartinActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaSanMartin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        botonListaAvellaneda.setBackground(new java.awt.Color(255, 255, 255));
        botonListaAvellaneda.setForeground(new java.awt.Color(0, 0, 0));
        botonListaAvellaneda.setBorderPainted(false);
        botonListaAvellaneda.setFocusCycleRoot(true);
        botonListaAvellaneda.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaAvellaneda.setRequestFocusEnabled(false);
        botonListaAvellaneda.setRolloverEnabled(false);
        botonListaAvellaneda.setSelected(true);
        botonListaAvellaneda.setVerifyInputWhenFocusTarget(false);
        botonListaAvellaneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaAvellanedaActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaAvellaneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        botonListaBelgrano.setBackground(new java.awt.Color(255, 255, 255));
        botonListaBelgrano.setForeground(new java.awt.Color(0, 0, 0));
        botonListaBelgrano.setBorderPainted(false);
        botonListaBelgrano.setFocusCycleRoot(true);
        botonListaBelgrano.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaBelgrano.setRequestFocusEnabled(false);
        botonListaBelgrano.setRolloverEnabled(false);
        botonListaBelgrano.setSelected(true);
        botonListaBelgrano.setVerifyInputWhenFocusTarget(false);
        botonListaBelgrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaBelgranoActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaBelgrano, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        botonListaGuemes.setBackground(new java.awt.Color(255, 255, 255));
        botonListaGuemes.setForeground(new java.awt.Color(0, 0, 0));
        botonListaGuemes.setBorderPainted(false);
        botonListaGuemes.setFocusCycleRoot(true);
        botonListaGuemes.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaGuemes.setRequestFocusEnabled(false);
        botonListaGuemes.setRolloverEnabled(false);
        botonListaGuemes.setSelected(true);
        botonListaGuemes.setVerifyInputWhenFocusTarget(false);
        botonListaGuemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaGuemesActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaGuemes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        botonListaMoreno.setBackground(new java.awt.Color(255, 255, 255));
        botonListaMoreno.setForeground(new java.awt.Color(0, 0, 0));
        botonListaMoreno.setBorderPainted(false);
        botonListaMoreno.setFocusCycleRoot(true);
        botonListaMoreno.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaMoreno.setRequestFocusEnabled(false);
        botonListaMoreno.setRolloverEnabled(false);
        botonListaMoreno.setSelected(true);
        botonListaMoreno.setVerifyInputWhenFocusTarget(false);
        botonListaMoreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaMorenoActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaMoreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, -1, -1));

        botonListaRivadavia.setBackground(new java.awt.Color(255, 255, 255));
        botonListaRivadavia.setForeground(new java.awt.Color(0, 0, 0));
        botonListaRivadavia.setBorderPainted(false);
        botonListaRivadavia.setFocusCycleRoot(true);
        botonListaRivadavia.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaRivadavia.setRequestFocusEnabled(false);
        botonListaRivadavia.setRolloverEnabled(false);
        botonListaRivadavia.setSelected(true);
        botonListaRivadavia.setVerifyInputWhenFocusTarget(false);
        botonListaRivadavia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaRivadaviaActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaRivadavia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        botonListaRoca.setBackground(new java.awt.Color(255, 255, 255));
        botonListaRoca.setForeground(new java.awt.Color(0, 0, 0));
        botonListaRoca.setBorderPainted(false);
        botonListaRoca.setFocusCycleRoot(true);
        botonListaRoca.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaRoca.setRequestFocusEnabled(false);
        botonListaRoca.setRolloverEnabled(false);
        botonListaRoca.setSelected(true);
        botonListaRoca.setVerifyInputWhenFocusTarget(false);
        botonListaRoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaRocaActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaRoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        botonListaPenia.setBackground(new java.awt.Color(255, 255, 255));
        botonListaPenia.setForeground(new java.awt.Color(0, 0, 0));
        botonListaPenia.setBorderPainted(false);
        botonListaPenia.setFocusCycleRoot(true);
        botonListaPenia.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaPenia.setRequestFocusEnabled(false);
        botonListaPenia.setRolloverEnabled(false);
        botonListaPenia.setSelected(true);
        botonListaPenia.setVerifyInputWhenFocusTarget(false);
        botonListaPenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaPeniaActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaPenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        botonListaSaavedra.setBackground(new java.awt.Color(255, 255, 255));
        botonListaSaavedra.setForeground(new java.awt.Color(0, 0, 0));
        botonListaSaavedra.setBorderPainted(false);
        botonListaSaavedra.setFocusCycleRoot(true);
        botonListaSaavedra.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaSaavedra.setRequestFocusEnabled(false);
        botonListaSaavedra.setRolloverEnabled(false);
        botonListaSaavedra.setSelected(true);
        botonListaSaavedra.setVerifyInputWhenFocusTarget(false);
        botonListaSaavedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaSaavedraActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaSaavedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        botonListaSarmiento.setBackground(new java.awt.Color(255, 255, 255));
        botonListaSarmiento.setForeground(new java.awt.Color(0, 0, 0));
        botonListaSarmiento.setBorderPainted(false);
        botonListaSarmiento.setFocusCycleRoot(true);
        botonListaSarmiento.setPreferredSize(new java.awt.Dimension(225, 225));
        botonListaSarmiento.setRequestFocusEnabled(false);
        botonListaSarmiento.setRolloverEnabled(false);
        botonListaSarmiento.setSelected(true);
        botonListaSarmiento.setVerifyInputWhenFocusTarget(false);
        botonListaSarmiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaSarmientoActionPerformed(evt);
            }
        });
        jPanel2.add(botonListaSarmiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, -1, -1));

        panelBarraOpciones.setBackground(new java.awt.Color(153, 153, 153));

        botonVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        botonVolverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left.png"))); // NOI18N
        botonVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("<html><body>Volver<br>Atrás</body></html>");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        botonVotoBlanco.setBackground(new java.awt.Color(51, 51, 51));
        botonVotoBlanco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonVotoBlanco.setForeground(new java.awt.Color(255, 255, 255));
        botonVotoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mail.png"))); // NOI18N
        botonVotoBlanco.setText("Votar en Blanco");
        botonVotoBlanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVotoBlanco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonVotoBlanco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonVotoBlanco.setIconTextGap(15);
        botonVotoBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotoBlancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVotoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVotoBlanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBarraOpcionesLayout = new javax.swing.GroupLayout(panelBarraOpciones);
        panelBarraOpciones.setLayout(panelBarraOpcionesLayout);
        panelBarraOpcionesLayout.setHorizontalGroup(
            panelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraOpcionesLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(botonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelBarraOpcionesLayout.setVerticalGroup(
            panelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraOpcionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(panelBarraOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelBarraOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1210, -1));

        jPanel14.setBackground(new java.awt.Color(6, 47, 110));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        logoProvincia11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoProvincia11.setForeground(new java.awt.Color(255, 255, 255));
        logoProvincia11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escudo-santafe.png"))); // NOI18N
        logoProvincia11.setText("Gobierno de la Provincia de Santa Fe ");

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Elecciones Presidenciales - Agosto 2023");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/santaFeGobierno.png"))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("SIMULADOR EDUCATIVO DE ELECCIONES");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoProvincia11)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel35)))
                .addGap(41, 41, 41)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(logoProvincia11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel37)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBoletaIngresarLayout = new javax.swing.GroupLayout(panelBoletaIngresar);
        panelBoletaIngresar.setLayout(panelBoletaIngresarLayout);
        panelBoletaIngresarLayout.setHorizontalGroup(
            panelBoletaIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoletaIngresarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBoletaIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        panelBoletaIngresarLayout.setVerticalGroup(
            panelBoletaIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoletaIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoletaIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoletaIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        this.setVisible(false);
        new ventanaVotar().setVisible(true);
    }//GEN-LAST:event_botonVolverAtrasActionPerformed

    private void botonVotoBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotoBlancoActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Voto en blanco", "Voto en blanco").setVisible(true);
    }//GEN-LAST:event_botonVotoBlancoActionPerformed

    private void botonListaSanMartinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaSanMartinActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("José de San Martín", "Juan Lavalle").setVisible(true);
    }//GEN-LAST:event_botonListaSanMartinActionPerformed

    private void botonListaAvellanedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaAvellanedaActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Nicolás Avellaneda", "Benjamin Franklin").setVisible(true);
    }//GEN-LAST:event_botonListaAvellanedaActionPerformed

    private void botonListaBelgranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaBelgranoActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Manuel Belgrano", "Franklin Roosevelt").setVisible(true);
    }//GEN-LAST:event_botonListaBelgranoActionPerformed

    private void botonListaGuemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaGuemesActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Martín Güemes", "Nikola Tesla").setVisible(true);
    }//GEN-LAST:event_botonListaGuemesActionPerformed

    private void botonListaMorenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaMorenoActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Mariano Moreno", "Carl Gauss").setVisible(true);
    }//GEN-LAST:event_botonListaMorenoActionPerformed

    private void botonListaRivadaviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaRivadaviaActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Bernardino Rivadavia", "Julio Cortázar").setVisible(true);
    }//GEN-LAST:event_botonListaRivadaviaActionPerformed

    private void botonListaRocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaRocaActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Julio Argentino Roca", "Isaac Newton").setVisible(true);
    }//GEN-LAST:event_botonListaRocaActionPerformed

    private void botonListaPeniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaPeniaActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Roque Saenz Peña","Carlos Pellegrini").setVisible(true);
    }//GEN-LAST:event_botonListaPeniaActionPerformed

    private void botonListaSaavedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaSaavedraActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Cornelio Saavedra","Bartolome Mitre").setVisible(true);
    }//GEN-LAST:event_botonListaSaavedraActionPerformed

    private void botonListaSarmientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaSarmientoActionPerformed
        this.setVisible(false);
        new ventanaVotoVisualizacion("Domingo F. Sarmiento","Juan Manuel de Rosas").setVisible(true);
    }//GEN-LAST:event_botonListaSarmientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListaAvellaneda;
    private javax.swing.JButton botonListaBelgrano;
    private javax.swing.JButton botonListaGuemes;
    private javax.swing.JButton botonListaMoreno;
    private javax.swing.JButton botonListaPenia;
    private javax.swing.JButton botonListaRivadavia;
    private javax.swing.JButton botonListaRoca;
    private javax.swing.JButton botonListaSaavedra;
    private javax.swing.JButton botonListaSanMartin;
    private javax.swing.JButton botonListaSarmiento;
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JButton botonVotoBlanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logoProvincia11;
    private javax.swing.JPanel panelBarraOpciones;
    private javax.swing.JPanel panelBoletaIngresar;
    // End of variables declaration//GEN-END:variables

    public class Fondo extends JPanel {

        private Image img;

        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource("/img/fondo.png")).getImage();
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
