package simulador;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ventanaVotoCategoriaVice extends javax.swing.JFrame {

    private Fondo fondo = new Fondo();
    String resultadoPresidente;
    ventanaVotoCategoriaPresi datos = new ventanaVotoCategoriaPresi();

    public ventanaVotoCategoriaVice(String presidente) {
        setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("ELECCIONES 2023");
        Image icono = new ImageIcon(getClass().getResource("/img/icono.png")).getImage();
        setIconImage(icono);
        resultadoPresidente = presidente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoletaIngresar = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelCandidatos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        retratoProcer = new javax.swing.JLabel();
        retratoProcer1 = new javax.swing.JLabel();
        retratoProcer2 = new javax.swing.JLabel();
        retratoProcer3 = new javax.swing.JLabel();
        retratoProcer4 = new javax.swing.JLabel();
        retratoProcer5 = new javax.swing.JLabel();
        retratoProcer6 = new javax.swing.JLabel();
        retratoProcer7 = new javax.swing.JLabel();
        retratoProcer8 = new javax.swing.JLabel();
        retratoProcer9 = new javax.swing.JLabel();
        partidoLista1 = new javax.swing.JLabel();
        partidoLista = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        partidoLista2 = new javax.swing.JLabel();
        partidoLista3 = new javax.swing.JLabel();
        partidoLista4 = new javax.swing.JLabel();
        partidoLista5 = new javax.swing.JLabel();
        partidoLista6 = new javax.swing.JLabel();
        partidoLista7 = new javax.swing.JLabel();
        partidoLista8 = new javax.swing.JLabel();
        partidoLista9 = new javax.swing.JLabel();
        botonTesla = new javax.swing.JButton();
        botonLavalle = new javax.swing.JButton();
        botonFranklin = new javax.swing.JButton();
        botonRoosevelt = new javax.swing.JButton();
        botonRosas = new javax.swing.JButton();
        botonCortazar = new javax.swing.JButton();
        botonNewton = new javax.swing.JButton();
        botonPellegrini = new javax.swing.JButton();
        botonMitre = new javax.swing.JButton();
        botonGauss = new javax.swing.JButton();
        panelBarraOpciones = new javax.swing.JPanel();
        botonVolverAtras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonVotoBlanco = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logoProvincia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        panelBoletaIngresar.setBackground(new java.awt.Color(255, 255, 255));
        panelBoletaIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelBoletaIngresar.setOpaque(false);

        panelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        panelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("VICEPRESIDENTE DE LA NACIÓN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelCandidatos.setBackground(new java.awt.Color(204, 204, 204));
        panelCandidatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("<html> <b>Vicepresidente: Julio Cortázar</b> <br> <center> Partido por la Lucha<center</html>");
        panelCandidatos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 50));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("<html> <b>Vicepresidente: Nikola Tesla</b> <br> <center> Partido Unidos del Sur<center</html>");
        panelCandidatos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 180, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("<html> <b>Vicepresidente: Juan Manuel de Rosas </b> <br> <center> Partido Unitario y Liberal<center</html>");
        panelCandidatos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 200, 50));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("<html> <b>Vicepresidente: Carl Gauss</b> <br> <center> Partido de la Independencia <center</html>");
        panelCandidatos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 190, 40));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("<html> <b>Vicepresidente: Franklin Roosevelt</b> <br> <center> Partido Unidos de la Plata<center</html>");
        panelCandidatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 190, 50));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("<html> <b>Vicepresidente: Benjamin Franklin</b> <br> <center> Partido por la Soberanía <center</html>");
        panelCandidatos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 200, 40));

        retratoProcer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lavalle.png"))); // NOI18N
        retratoProcer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 120));

        retratoProcer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Franklin.png"))); // NOI18N
        retratoProcer1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 120));

        retratoProcer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Roosevelt.png"))); // NOI18N
        retratoProcer2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 100, 120));

        retratoProcer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tesla.png"))); // NOI18N
        retratoProcer3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 100, 120));

        retratoProcer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gauss.png"))); // NOI18N
        retratoProcer4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 100, 120));

        retratoProcer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cortazar.png"))); // NOI18N
        retratoProcer5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 120));

        retratoProcer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Newton.png"))); // NOI18N
        retratoProcer6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, 120));

        retratoProcer7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pellegrini.png"))); // NOI18N
        retratoProcer7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 100, 120));

        retratoProcer8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mitre.png"))); // NOI18N
        retratoProcer8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 100, 120));

        retratoProcer9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rosas.png"))); // NOI18N
        retratoProcer9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        retratoProcer9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCandidatos.add(retratoProcer9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 100, 120));

        partidoLista1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista1.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista1.setText("LISTA: 135B");
        panelCandidatos.add(partidoLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 250, -1, -1));

        partidoLista.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista.setText("LISTA: 135A");
        panelCandidatos.add(partidoLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("<html> <b>Vicepresidente: Isaac Newton</b> <br> <center> Partido Autonomista Nacional<center</html>");
        panelCandidatos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, 50));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("<html> <b>Vicepresidente: Juan Lavalle</b> <br> <center> Partido por la Libertad  y la Independencia <center></html>");
        panelCandidatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 60));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("<html> <b>Vicepresidente: Carlos Pellegrini</b> <br> <center> Partido Modernista<center</html>");
        panelCandidatos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 190, 50));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("<html> <b>Vicepresidente: Bartolome Mitre</b> <br> <center> Partido del Ejercito Patriotico<center</html>");
        panelCandidatos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 190, 40));

        partidoLista2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista2.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista2.setText("LISTA: 130B");
        panelCandidatos.add(partidoLista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        partidoLista3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista3.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista3.setText("LISTA: 131A");
        panelCandidatos.add(partidoLista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        partidoLista4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista4.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista4.setText("LISTA: 125C");
        panelCandidatos.add(partidoLista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        partidoLista5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista5.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista5.setText("LISTA: 132B");
        panelCandidatos.add(partidoLista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        partidoLista6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista6.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista6.setText("LISTA: 132A");
        panelCandidatos.add(partidoLista6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        partidoLista7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista7.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista7.setText("LISTA: 137A");
        panelCandidatos.add(partidoLista7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        partidoLista8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista8.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista8.setText("LISTA: 123B");
        panelCandidatos.add(partidoLista8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        partidoLista9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partidoLista9.setForeground(new java.awt.Color(51, 51, 51));
        partidoLista9.setText("LISTA: 137B");
        panelCandidatos.add(partidoLista9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, -1, -1));

        botonTesla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTesla.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonTesla.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonTesla.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonTesla.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonTesla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTeslaActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonTesla, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 209, 215));

        botonLavalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonLavalle.setForeground(new java.awt.Color(0, 0, 0));
        botonLavalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLavalle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonLavalle.setIconTextGap(6);
        botonLavalle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonLavalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLavalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLavalleActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonLavalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 215));

        botonFranklin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFranklin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonFranklin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonFranklin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonFranklin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonFranklin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFranklinActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonFranklin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 209, 215));

        botonRoosevelt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRoosevelt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonRoosevelt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonRoosevelt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonRoosevelt.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonRoosevelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRooseveltActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonRoosevelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 209, 215));

        botonRosas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRosas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonRosas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonRosas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonRosas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonRosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRosasActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonRosas, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 209, 215));

        botonCortazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCortazar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonCortazar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonCortazar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonCortazar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonCortazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCortazarActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonCortazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 209, 215));

        botonNewton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNewton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonNewton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonNewton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonNewton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNewtonActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 209, 215));

        botonPellegrini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPellegrini.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPellegrini.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonPellegrini.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonPellegrini.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonPellegrini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPellegriniActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonPellegrini, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 209, 215));

        botonMitre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMitre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonMitre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonMitre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonMitre.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonMitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMitreActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonMitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 209, 215));

        botonGauss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGauss.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonGauss.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonGauss.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botonGauss.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botonGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGaussActionPerformed(evt);
            }
        });
        panelCandidatos.add(botonGauss, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 209, 215));

        panelBarraOpciones.setBackground(new java.awt.Color(153, 153, 153));

        botonVolverAtras.setBackground(new java.awt.Color(255, 255, 255));
        botonVolverAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left.png"))); // NOI18N
        botonVolverAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<html><body>Volver<br>Atrás</body></html>");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        botonVotoBlanco.setBackground(new java.awt.Color(51, 51, 51));
        botonVotoBlanco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonVotoBlanco.setForeground(new java.awt.Color(255, 255, 255));
        botonVotoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mail.png"))); // NOI18N
        botonVotoBlanco.setText("Votar en Blanco");
        botonVotoBlanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVotoBlanco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonVotoBlanco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonVotoBlanco.setIconTextGap(15);
        botonVotoBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotoBlancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVotoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVotoBlanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBarraOpcionesLayout = new javax.swing.GroupLayout(panelBarraOpciones);
        panelBarraOpciones.setLayout(panelBarraOpcionesLayout);
        panelBarraOpcionesLayout.setHorizontalGroup(
            panelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraOpcionesLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(botonVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelBarraOpcionesLayout.setVerticalGroup(
            panelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBarraOpcionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelBarraOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(6, 47, 110));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        logoProvincia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoProvincia.setForeground(new java.awt.Color(255, 255, 255));
        logoProvincia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escudo-santafe.png"))); // NOI18N
        logoProvincia.setText("Gobierno de la Provincia de Santa Fe ");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elecciones Presidenciales - Agosto 2023");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/santaFeGobierno.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIMULADOR EDUCATIVO DE ELECCIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(logoProvincia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBoletaIngresarLayout = new javax.swing.GroupLayout(panelBoletaIngresar);
        panelBoletaIngresar.setLayout(panelBoletaIngresarLayout);
        panelBoletaIngresarLayout.setHorizontalGroup(
            panelBoletaIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoletaIngresarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBoletaIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBoletaIngresarLayout.setVerticalGroup(
            panelBoletaIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoletaIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoletaIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoletaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        this.setVisible(false);
        new ventanaVotoCategoriaPresi().setVisible(true);
    }//GEN-LAST:event_botonVolverAtrasActionPerformed

    private void botonLavalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLavalleActionPerformed
        this.setVisible(false);
        String vice = "Juan Lavalle";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonLavalleActionPerformed

    private void botonVotoBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotoBlancoActionPerformed
        this.setVisible(false);
        String vice = "Voto en Blanco";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonVotoBlancoActionPerformed

    private void botonFranklinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFranklinActionPerformed
        this.setVisible(false);
        String vice = "Benjamin Franklin";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonFranklinActionPerformed

    private void botonRooseveltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRooseveltActionPerformed
        this.setVisible(false);
        String vice = "Franklin Roosevelt";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonRooseveltActionPerformed

    private void botonTeslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTeslaActionPerformed
        this.setVisible(false);
        String vice = "Nikola Tesla";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonTeslaActionPerformed

    private void botonGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGaussActionPerformed
        this.setVisible(false);
        String vice = "Carl Gauss";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonGaussActionPerformed

    private void botonCortazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCortazarActionPerformed
        this.setVisible(false);
        String vice = "Julio Cortázar";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonCortazarActionPerformed

    private void botonNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNewtonActionPerformed
        this.setVisible(false);
        String vice = "Isaac Newton";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonNewtonActionPerformed

    private void botonPellegriniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPellegriniActionPerformed
        this.setVisible(false);
        String vice = "Carlos Pellegrini";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonPellegriniActionPerformed

    private void botonMitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMitreActionPerformed
        this.setVisible(false);
        String vice = "Bartolome Mitre";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonMitreActionPerformed

    private void botonRosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRosasActionPerformed
        this.setVisible(false);
        String vice = "Juan Manuel de Rosas";
        new ventanaVotoVisualizacion(resultadoPresidente, vice).setVisible(true);
    }//GEN-LAST:event_botonRosasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCortazar;
    private javax.swing.JButton botonFranklin;
    private javax.swing.JButton botonGauss;
    private javax.swing.JButton botonLavalle;
    private javax.swing.JButton botonMitre;
    private javax.swing.JButton botonNewton;
    private javax.swing.JButton botonPellegrini;
    private javax.swing.JButton botonRoosevelt;
    private javax.swing.JButton botonRosas;
    private javax.swing.JButton botonTesla;
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JButton botonVotoBlanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logoProvincia;
    private javax.swing.JPanel panelBarraOpciones;
    private javax.swing.JPanel panelBoletaIngresar;
    private javax.swing.JPanel panelCandidatos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel partidoLista;
    private javax.swing.JLabel partidoLista1;
    private javax.swing.JLabel partidoLista2;
    private javax.swing.JLabel partidoLista3;
    private javax.swing.JLabel partidoLista4;
    private javax.swing.JLabel partidoLista5;
    private javax.swing.JLabel partidoLista6;
    private javax.swing.JLabel partidoLista7;
    private javax.swing.JLabel partidoLista8;
    private javax.swing.JLabel partidoLista9;
    private javax.swing.JLabel retratoProcer;
    private javax.swing.JLabel retratoProcer1;
    private javax.swing.JLabel retratoProcer2;
    private javax.swing.JLabel retratoProcer3;
    private javax.swing.JLabel retratoProcer4;
    private javax.swing.JLabel retratoProcer5;
    private javax.swing.JLabel retratoProcer6;
    private javax.swing.JLabel retratoProcer7;
    private javax.swing.JLabel retratoProcer8;
    private javax.swing.JLabel retratoProcer9;
    // End of variables declaration//GEN-END:variables

    public class Fondo extends JPanel {

        private Image img;

        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource("/img/fondo.png")).getImage();
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
